/**
 * Support Tickets Service
 * Handles ticket creation, listing, updating, and messaging.
 */
import pool from "../db/pool.js";
import { getIo } from "../socket.js";
import { sendTelegramMessage } from "./telegram.service.js";

export const supportService = {
  /**
   * List tickets with filters
   */
  async listTickets({
    clientId,
    serviceId,
    status,
    priority,
    assignedTo,
    search,
    page = 1,
    limit = 20,
  } = {}) {
    let query = `
      SELECT
        t.id, t.ticket_number, t.client_id, t.hosting_service_id, t.subject,
        t.priority, t.status, t.assigned_to, t.created_by,
        t.last_message_at, t.resolved_at, t.closed_at, t.created_at, t.updated_at,
        c.name as client_name, c.company as client_company,
        hs.domain as service_domain,
        u.name as assigned_user_name
      FROM support_tickets t
      LEFT JOIN clients c ON t.client_id = c.id
      LEFT JOIN hosting_services hs ON t.hosting_service_id = hs.id
      LEFT JOIN users u ON t.assigned_to = u.id
      WHERE 1=1
    `;
    const params = [];

    if (clientId) {
      query += ` AND t.client_id = $${params.length + 1}`;
      params.push(clientId);
    }

    if (serviceId) {
      query += ` AND t.hosting_service_id = $${params.length + 1}`;
      params.push(serviceId);
    }

    if (status) {
      query += ` AND t.status = $${params.length + 1}`;
      params.push(status);
    }

    if (priority) {
      query += ` AND t.priority = $${params.length + 1}`;
      params.push(priority);
    }

    if (assignedTo) {
      query += ` AND t.assigned_to = $${params.length + 1}`;
      params.push(assignedTo);
    }

    if (search) {
      query += ` AND (t.ticket_number ILIKE $${params.length + 1} OR t.subject ILIKE $${params.length + 1})`;
      const searchTerm = `%${search}%`;
      params.push(searchTerm, searchTerm);
    }

    const offset = (page - 1) * limit;
    query += ` ORDER BY t.created_at DESC LIMIT $${params.length + 1} OFFSET $${params.length + 2}`;
    params.push(limit, offset);

    const result = await pool.query(query, params);

    // Contar total
    let countQuery = `SELECT COUNT(*) FROM support_tickets t WHERE 1=1`;
    const countParams = [];
    let paramIndex = 1;

    if (clientId) {
      countQuery += ` AND t.client_id = $${paramIndex++}`;
      countParams.push(clientId);
    }
    if (serviceId) {
      countQuery += ` AND t.hosting_service_id = $${paramIndex++}`;
      countParams.push(serviceId);
    }
    if (status) {
      countQuery += ` AND t.status = $${paramIndex++}`;
      countParams.push(status);
    }
    if (priority) {
      countQuery += ` AND t.priority = $${paramIndex++}`;
      countParams.push(priority);
    }
    if (assignedTo) {
      countQuery += ` AND t.assigned_to = $${paramIndex++}`;
      countParams.push(assignedTo);
    }
    if (search) {
      countQuery += ` AND (t.ticket_number ILIKE $${paramIndex++} OR t.subject ILIKE $${paramIndex++})`;
      const searchTerm = `%${search}%`;
      countParams.push(searchTerm, searchTerm);
    }

    const countResult = await pool.query(countQuery, countParams);
    const total = parseInt(countResult.rows[0].count, 10);

    return {
      data: result.rows,
      page,
      limit,
      total,
      pages: Math.ceil(total / limit),
    };
  },

  /**
   * Get single ticket with messages
   */
  async getTicket(id) {
    const ticketQuery = `
      SELECT
        t.id, t.ticket_number, t.client_id, t.hosting_service_id, t.subject,
        t.priority, t.status, t.assigned_to, t.created_by,
        t.last_message_at, t.resolved_at, t.closed_at, t.created_at, t.updated_at,
        c.name as client_name, c.company as client_company,
        hs.domain as service_domain,
        u.name as assigned_user_name
      FROM support_tickets t
      LEFT JOIN clients c ON t.client_id = c.id
      LEFT JOIN hosting_services hs ON t.hosting_service_id = hs.id
      LEFT JOIN users u ON t.assigned_to = u.id
      WHERE t.id = $1
    `;
    const ticketResult = await pool.query(ticketQuery, [id]);

    if (ticketResult.rows.length === 0) {
      throw new Error("Ticket not found");
    }

    const ticket = ticketResult.rows[0];

    // Get messages
    const messagesQuery = `
      SELECT * FROM support_ticket_messages
      WHERE ticket_id = $1
      ORDER BY created_at ASC
    `;
    const messagesResult = await pool.query(messagesQuery, [id]);

    return {
      ...ticket,
      messages: messagesResult.rows,
    };
  },

  /**
   * Create ticket (ticket_number auto-generated by DB)
   */
  async createTicket({ clientId, serviceId, subject, priority = "normal", createdBy }) {
    const query = `
      INSERT INTO support_tickets
        (client_id, hosting_service_id, subject, priority, created_by)
      VALUES ($1, $2, $3, $4, $5)
      RETURNING *
    `;

    const result = await pool.query(query, [
      clientId,
      serviceId || null,
      subject,
      priority,
      createdBy || null,
    ]);

    const ticket = result.rows[0];
    sendTelegramMessage(
      `🎫 <b>Ticket nuevo</b> #${ticket.ticket_number}\n${subject}\nPrioridad: ${priority}`,
    );

    return ticket;
  },

  /**
   * Update ticket (status, priority, assign)
   */
  async updateTicket(id, patch) {
    const allowed = ["subject", "priority", "status", "assigned_to"];
    const updates = [];
    const values = [];
    let paramIndex = 1;

    Object.entries(patch).forEach(([key, value]) => {
      if (allowed.includes(key)) {
        updates.push(`${key} = $${paramIndex++}`);
        values.push(value);
      }
    });

    if (updates.length === 0) {
      return this.getTicket(id);
    }

    values.push(id);
    const query = `
      UPDATE support_tickets
      SET ${updates.join(", ")}
      WHERE id = $${paramIndex}
      RETURNING *
    `;

    const result = await pool.query(query, values);
    if (result.rows.length === 0) throw new Error("Ticket not found");

    return result.rows[0];
  },

  /**
   * Add message to ticket
   */
  async addMessage({
    ticketId,
    senderUserId,
    senderName,
    senderRole,
    message,
    isInternal = false,
    attachmentUrl = null,
    attachmentType = null,
    attachmentName = null,
  }) {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");

      // Insert message
      const msgQuery = `
        INSERT INTO support_ticket_messages
          (ticket_id, sender_user_id, sender_name, sender_role, message, is_internal,
           attachment_url, attachment_type, attachment_name)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        RETURNING *
      `;
      const msgResult = await client.query(msgQuery, [
        ticketId,
        senderUserId || null,
        senderName,
        senderRole,
        message || null,
        isInternal,
        attachmentUrl,
        attachmentType,
        attachmentName,
      ]);

      // Update ticket last_message_at
      const updateQuery = `
        UPDATE support_tickets
        SET last_message_at = now()
        WHERE id = $1
      `;
      await client.query(updateQuery, [ticketId]);

      await client.query("COMMIT");

      const msg = msgResult.rows[0];
      // Emitir en tiempo real a todos los que están viendo este ticket
      getIo()?.to(`ticket:${ticketId}`).emit("ticket:message", msg);

      // Avisar a staff por Telegram solo cuando el mensaje viene del cliente
      if (senderRole === "cliente" && !isInternal) {
        sendTelegramMessage(
          `💬 <b>Respuesta de cliente</b> en ticket\n${senderName}: ${(message || "[archivo adjunto]").slice(0, 200)}`,
        );
      }

      return msg;
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }
  },

  /**
   * Assign ticket
   */
  async assignTicket(id, assignedTo) {
    const query = `
      UPDATE support_tickets
      SET assigned_to = $1
      WHERE id = $2
      RETURNING *
    `;
    const result = await pool.query(query, [assignedTo, id]);
    if (result.rows.length === 0) throw new Error("Ticket not found");
    return result.rows[0];
  },

  /**
   * Resolve ticket
   */
  async resolveTicket(id) {
    const query = `
      UPDATE support_tickets
      SET status = 'resolved', resolved_at = now()
      WHERE id = $1
      RETURNING *
    `;
    const result = await pool.query(query, [id]);
    if (result.rows.length === 0) throw new Error("Ticket not found");
    return result.rows[0];
  },

  /**
   * Close ticket
   */
  async closeTicket(id) {
    const query = `
      UPDATE support_tickets
      SET status = 'closed', closed_at = now()
      WHERE id = $1
      RETURNING *
    `;
    const result = await pool.query(query, [id]);
    if (result.rows.length === 0) throw new Error("Ticket not found");
    return result.rows[0];
  },

  /**
   * Delete ticket and all its messages
   */
  async deleteTicket(id) {
    const result = await pool.query(
      "DELETE FROM support_tickets WHERE id = $1 RETURNING id",
      [id],
    );
    if (result.rows.length === 0) throw new Error("Ticket not found");
  },
};
