/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupInicialRouteImport } from './routes/setup-inicial'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as PortalTicketsRouteImport } from './routes/portal.tickets'
import { Route as PortalPagosRouteImport } from './routes/portal.pagos'
import { Route as PortalDominiosRouteImport } from './routes/portal.dominios'
import { Route as PortalDatosRouteImport } from './routes/portal.datos'
import { Route as PortalAvisosRouteImport } from './routes/portal.avisos'
import { Route as AdminWorkflowsRouteImport } from './routes/_admin.workflows'
import { Route as AdminUsuariosRouteImport } from './routes/_admin.usuarios'
import { Route as AdminTareasRouteImport } from './routes/_admin.tareas'
import { Route as AdminSoporteRouteImport } from './routes/_admin.soporte'
import { Route as AdminPlantillasRouteImport } from './routes/_admin.plantillas'
import { Route as AdminPlanesRouteImport } from './routes/_admin.planes'
import { Route as AdminPerfilRouteImport } from './routes/_admin.perfil'
import { Route as AdminPagosRouteImport } from './routes/_admin.pagos'
import { Route as AdminOperacionesRouteImport } from './routes/_admin.operaciones'
import { Route as AdminOnboardingRouteImport } from './routes/_admin.onboarding'
import { Route as AdminNotificacionesRouteImport } from './routes/_admin.notificaciones'
import { Route as AdminNegocioRouteImport } from './routes/_admin.negocio'
import { Route as AdminHestiaRouteImport } from './routes/_admin.hestia'
import { Route as AdminEmailLogsRouteImport } from './routes/_admin.email-logs'
import { Route as AdminDominiosRouteImport } from './routes/_admin.dominios'
import { Route as AdminDiagnosticoRouteImport } from './routes/_admin.diagnostico'
import { Route as AdminConfiguracionRouteImport } from './routes/_admin.configuracion'
import { Route as AdminCobranzaRouteImport } from './routes/_admin.cobranza'
import { Route as AdminBienvenidaRouteImport } from './routes/_admin.bienvenida'
import { Route as AdminBackupsRouteImport } from './routes/_admin.backups'
import { Route as AdminAvisosRouteImport } from './routes/_admin.avisos'
import { Route as AdminAutomatizacionesRouteImport } from './routes/_admin.automatizaciones'
import { Route as AdminAuditoriaRouteImport } from './routes/_admin.auditoria'
import { Route as AdminArquitecturaRouteImport } from './routes/_admin.arquitectura'
import { Route as AdminServiciosIndexRouteImport } from './routes/_admin.servicios.index'
import { Route as AdminClientesIndexRouteImport } from './routes/_admin.clientes.index'
import { Route as AdminTareasIdRouteImport } from './routes/_admin.tareas.$id'
import { Route as AdminSoporteIdRouteImport } from './routes/_admin.soporte.$id'
import { Route as AdminServiciosIdRouteImport } from './routes/_admin.servicios.$id'
import { Route as AdminDominiosIdRouteImport } from './routes/_admin.dominios.$id'
import { Route as AdminClientesIdRouteImport } from './routes/_admin.clientes.$id'

const SetupInicialRoute = SetupInicialRouteImport.update({
  id: '/setup-inicial',
  path: '/setup-inicial',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PortalTicketsRoute = PortalTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPagosRoute = PortalPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDominiosRoute = PortalDominiosRouteImport.update({
  id: '/dominios',
  path: '/dominios',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDatosRoute = PortalDatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAvisosRoute = PortalAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => PortalRoute,
} as any)
const AdminWorkflowsRoute = AdminWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTareasRoute = AdminTareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSoporteRoute = AdminSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlantillasRoute = AdminPlantillasRouteImport.update({
  id: '/plantillas',
  path: '/plantillas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanesRoute = AdminPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagosRoute = AdminPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperacionesRoute = AdminOperacionesRouteImport.update({
  id: '/operaciones',
  path: '/operaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacionesRoute = AdminNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNegocioRoute = AdminNegocioRouteImport.update({
  id: '/negocio',
  path: '/negocio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHestiaRoute = AdminHestiaRouteImport.update({
  id: '/hestia',
  path: '/hestia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailLogsRoute = AdminEmailLogsRouteImport.update({
  id: '/email-logs',
  path: '/email-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDominiosRoute = AdminDominiosRouteImport.update({
  id: '/dominios',
  path: '/dominios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticoRoute = AdminDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCobranzaRoute = AdminCobranzaRouteImport.update({
  id: '/cobranza',
  path: '/cobranza',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBienvenidaRoute = AdminBienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvisosRoute = AdminAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomatizacionesRoute = AdminAutomatizacionesRouteImport.update({
  id: '/automatizaciones',
  path: '/automatizaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArquitecturaRoute = AdminArquitecturaRouteImport.update({
  id: '/arquitectura',
  path: '/arquitectura',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiciosIndexRoute = AdminServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTareasIdRoute = AdminTareasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTareasRoute,
} as any)
const AdminSoporteIdRoute = AdminSoporteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSoporteRoute,
} as any)
const AdminServiciosIdRoute = AdminServiciosIdRouteImport.update({
  id: '/servicios/$id',
  path: '/servicios/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDominiosIdRoute = AdminDominiosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminDominiosRoute,
} as any)
const AdminClientesIdRoute = AdminClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/recuperar': typeof RecuperarRoute
  '/setup-inicial': typeof SetupInicialRoute
  '/arquitectura': typeof AdminArquitecturaRoute
  '/auditoria': typeof AdminAuditoriaRoute
  '/automatizaciones': typeof AdminAutomatizacionesRoute
  '/avisos': typeof AdminAvisosRoute
  '/backups': typeof AdminBackupsRoute
  '/bienvenida': typeof AdminBienvenidaRoute
  '/cobranza': typeof AdminCobranzaRoute
  '/configuracion': typeof AdminConfiguracionRoute
  '/diagnostico': typeof AdminDiagnosticoRoute
  '/dominios': typeof AdminDominiosRouteWithChildren
  '/email-logs': typeof AdminEmailLogsRoute
  '/hestia': typeof AdminHestiaRoute
  '/negocio': typeof AdminNegocioRoute
  '/notificaciones': typeof AdminNotificacionesRoute
  '/onboarding': typeof AdminOnboardingRoute
  '/operaciones': typeof AdminOperacionesRoute
  '/pagos': typeof AdminPagosRoute
  '/perfil': typeof AdminPerfilRoute
  '/planes': typeof AdminPlanesRoute
  '/plantillas': typeof AdminPlantillasRoute
  '/soporte': typeof AdminSoporteRouteWithChildren
  '/tareas': typeof AdminTareasRouteWithChildren
  '/usuarios': typeof AdminUsuariosRoute
  '/workflows': typeof AdminWorkflowsRoute
  '/portal/avisos': typeof PortalAvisosRoute
  '/portal/datos': typeof PortalDatosRoute
  '/portal/dominios': typeof PortalDominiosRoute
  '/portal/pagos': typeof PortalPagosRoute
  '/portal/tickets': typeof PortalTicketsRoute
  '/portal/': typeof PortalIndexRoute
  '/clientes/$id': typeof AdminClientesIdRoute
  '/dominios/$id': typeof AdminDominiosIdRoute
  '/servicios/$id': typeof AdminServiciosIdRoute
  '/soporte/$id': typeof AdminSoporteIdRoute
  '/tareas/$id': typeof AdminTareasIdRoute
  '/clientes/': typeof AdminClientesIndexRoute
  '/servicios/': typeof AdminServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/setup-inicial': typeof SetupInicialRoute
  '/arquitectura': typeof AdminArquitecturaRoute
  '/auditoria': typeof AdminAuditoriaRoute
  '/automatizaciones': typeof AdminAutomatizacionesRoute
  '/avisos': typeof AdminAvisosRoute
  '/backups': typeof AdminBackupsRoute
  '/bienvenida': typeof AdminBienvenidaRoute
  '/cobranza': typeof AdminCobranzaRoute
  '/configuracion': typeof AdminConfiguracionRoute
  '/diagnostico': typeof AdminDiagnosticoRoute
  '/dominios': typeof AdminDominiosRouteWithChildren
  '/email-logs': typeof AdminEmailLogsRoute
  '/hestia': typeof AdminHestiaRoute
  '/negocio': typeof AdminNegocioRoute
  '/notificaciones': typeof AdminNotificacionesRoute
  '/onboarding': typeof AdminOnboardingRoute
  '/operaciones': typeof AdminOperacionesRoute
  '/pagos': typeof AdminPagosRoute
  '/perfil': typeof AdminPerfilRoute
  '/planes': typeof AdminPlanesRoute
  '/plantillas': typeof AdminPlantillasRoute
  '/soporte': typeof AdminSoporteRouteWithChildren
  '/tareas': typeof AdminTareasRouteWithChildren
  '/usuarios': typeof AdminUsuariosRoute
  '/workflows': typeof AdminWorkflowsRoute
  '/portal/avisos': typeof PortalAvisosRoute
  '/portal/datos': typeof PortalDatosRoute
  '/portal/dominios': typeof PortalDominiosRoute
  '/portal/pagos': typeof PortalPagosRoute
  '/portal/tickets': typeof PortalTicketsRoute
  '/': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/clientes/$id': typeof AdminClientesIdRoute
  '/dominios/$id': typeof AdminDominiosIdRoute
  '/servicios/$id': typeof AdminServiciosIdRoute
  '/soporte/$id': typeof AdminSoporteIdRoute
  '/tareas/$id': typeof AdminTareasIdRoute
  '/clientes': typeof AdminClientesIndexRoute
  '/servicios': typeof AdminServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/recuperar': typeof RecuperarRoute
  '/setup-inicial': typeof SetupInicialRoute
  '/_admin/arquitectura': typeof AdminArquitecturaRoute
  '/_admin/auditoria': typeof AdminAuditoriaRoute
  '/_admin/automatizaciones': typeof AdminAutomatizacionesRoute
  '/_admin/avisos': typeof AdminAvisosRoute
  '/_admin/backups': typeof AdminBackupsRoute
  '/_admin/bienvenida': typeof AdminBienvenidaRoute
  '/_admin/cobranza': typeof AdminCobranzaRoute
  '/_admin/configuracion': typeof AdminConfiguracionRoute
  '/_admin/diagnostico': typeof AdminDiagnosticoRoute
  '/_admin/dominios': typeof AdminDominiosRouteWithChildren
  '/_admin/email-logs': typeof AdminEmailLogsRoute
  '/_admin/hestia': typeof AdminHestiaRoute
  '/_admin/negocio': typeof AdminNegocioRoute
  '/_admin/notificaciones': typeof AdminNotificacionesRoute
  '/_admin/onboarding': typeof AdminOnboardingRoute
  '/_admin/operaciones': typeof AdminOperacionesRoute
  '/_admin/pagos': typeof AdminPagosRoute
  '/_admin/perfil': typeof AdminPerfilRoute
  '/_admin/planes': typeof AdminPlanesRoute
  '/_admin/plantillas': typeof AdminPlantillasRoute
  '/_admin/soporte': typeof AdminSoporteRouteWithChildren
  '/_admin/tareas': typeof AdminTareasRouteWithChildren
  '/_admin/usuarios': typeof AdminUsuariosRoute
  '/_admin/workflows': typeof AdminWorkflowsRoute
  '/portal/avisos': typeof PortalAvisosRoute
  '/portal/datos': typeof PortalDatosRoute
  '/portal/dominios': typeof PortalDominiosRoute
  '/portal/pagos': typeof PortalPagosRoute
  '/portal/tickets': typeof PortalTicketsRoute
  '/_admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_admin/clientes/$id': typeof AdminClientesIdRoute
  '/_admin/dominios/$id': typeof AdminDominiosIdRoute
  '/_admin/servicios/$id': typeof AdminServiciosIdRoute
  '/_admin/soporte/$id': typeof AdminSoporteIdRoute
  '/_admin/tareas/$id': typeof AdminTareasIdRoute
  '/_admin/clientes/': typeof AdminClientesIndexRoute
  '/_admin/servicios/': typeof AdminServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/recuperar'
    | '/setup-inicial'
    | '/arquitectura'
    | '/auditoria'
    | '/automatizaciones'
    | '/avisos'
    | '/backups'
    | '/bienvenida'
    | '/cobranza'
    | '/configuracion'
    | '/diagnostico'
    | '/dominios'
    | '/email-logs'
    | '/hestia'
    | '/negocio'
    | '/notificaciones'
    | '/onboarding'
    | '/operaciones'
    | '/pagos'
    | '/perfil'
    | '/planes'
    | '/plantillas'
    | '/soporte'
    | '/tareas'
    | '/usuarios'
    | '/workflows'
    | '/portal/avisos'
    | '/portal/datos'
    | '/portal/dominios'
    | '/portal/pagos'
    | '/portal/tickets'
    | '/portal/'
    | '/clientes/$id'
    | '/dominios/$id'
    | '/servicios/$id'
    | '/soporte/$id'
    | '/tareas/$id'
    | '/clientes/'
    | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recuperar'
    | '/setup-inicial'
    | '/arquitectura'
    | '/auditoria'
    | '/automatizaciones'
    | '/avisos'
    | '/backups'
    | '/bienvenida'
    | '/cobranza'
    | '/configuracion'
    | '/diagnostico'
    | '/dominios'
    | '/email-logs'
    | '/hestia'
    | '/negocio'
    | '/notificaciones'
    | '/onboarding'
    | '/operaciones'
    | '/pagos'
    | '/perfil'
    | '/planes'
    | '/plantillas'
    | '/soporte'
    | '/tareas'
    | '/usuarios'
    | '/workflows'
    | '/portal/avisos'
    | '/portal/datos'
    | '/portal/dominios'
    | '/portal/pagos'
    | '/portal/tickets'
    | '/'
    | '/portal'
    | '/clientes/$id'
    | '/dominios/$id'
    | '/servicios/$id'
    | '/soporte/$id'
    | '/tareas/$id'
    | '/clientes'
    | '/servicios'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/portal'
    | '/recuperar'
    | '/setup-inicial'
    | '/_admin/arquitectura'
    | '/_admin/auditoria'
    | '/_admin/automatizaciones'
    | '/_admin/avisos'
    | '/_admin/backups'
    | '/_admin/bienvenida'
    | '/_admin/cobranza'
    | '/_admin/configuracion'
    | '/_admin/diagnostico'
    | '/_admin/dominios'
    | '/_admin/email-logs'
    | '/_admin/hestia'
    | '/_admin/negocio'
    | '/_admin/notificaciones'
    | '/_admin/onboarding'
    | '/_admin/operaciones'
    | '/_admin/pagos'
    | '/_admin/perfil'
    | '/_admin/planes'
    | '/_admin/plantillas'
    | '/_admin/soporte'
    | '/_admin/tareas'
    | '/_admin/usuarios'
    | '/_admin/workflows'
    | '/portal/avisos'
    | '/portal/datos'
    | '/portal/dominios'
    | '/portal/pagos'
    | '/portal/tickets'
    | '/_admin/'
    | '/portal/'
    | '/_admin/clientes/$id'
    | '/_admin/dominios/$id'
    | '/_admin/servicios/$id'
    | '/_admin/soporte/$id'
    | '/_admin/tareas/$id'
    | '/_admin/clientes/'
    | '/_admin/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  RecuperarRoute: typeof RecuperarRoute
  SetupInicialRoute: typeof SetupInicialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-inicial': {
      id: '/setup-inicial'
      path: '/setup-inicial'
      fullPath: '/setup-inicial'
      preLoaderRoute: typeof SetupInicialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/tickets': {
      id: '/portal/tickets'
      path: '/tickets'
      fullPath: '/portal/tickets'
      preLoaderRoute: typeof PortalTicketsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/pagos': {
      id: '/portal/pagos'
      path: '/pagos'
      fullPath: '/portal/pagos'
      preLoaderRoute: typeof PortalPagosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dominios': {
      id: '/portal/dominios'
      path: '/dominios'
      fullPath: '/portal/dominios'
      preLoaderRoute: typeof PortalDominiosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/datos': {
      id: '/portal/datos'
      path: '/datos'
      fullPath: '/portal/datos'
      preLoaderRoute: typeof PortalDatosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/avisos': {
      id: '/portal/avisos'
      path: '/avisos'
      fullPath: '/portal/avisos'
      preLoaderRoute: typeof PortalAvisosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_admin/workflows': {
      id: '/_admin/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AdminWorkflowsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/usuarios': {
      id: '/_admin/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tareas': {
      id: '/_admin/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof AdminTareasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/soporte': {
      id: '/_admin/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof AdminSoporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/plantillas': {
      id: '/_admin/plantillas'
      path: '/plantillas'
      fullPath: '/plantillas'
      preLoaderRoute: typeof AdminPlantillasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/planes': {
      id: '/_admin/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof AdminPlanesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/perfil': {
      id: '/_admin/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pagos': {
      id: '/_admin/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof AdminPagosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/operaciones': {
      id: '/_admin/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof AdminOperacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/onboarding': {
      id: '/_admin/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notificaciones': {
      id: '/_admin/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AdminNotificacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/negocio': {
      id: '/_admin/negocio'
      path: '/negocio'
      fullPath: '/negocio'
      preLoaderRoute: typeof AdminNegocioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/hestia': {
      id: '/_admin/hestia'
      path: '/hestia'
      fullPath: '/hestia'
      preLoaderRoute: typeof AdminHestiaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/email-logs': {
      id: '/_admin/email-logs'
      path: '/email-logs'
      fullPath: '/email-logs'
      preLoaderRoute: typeof AdminEmailLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dominios': {
      id: '/_admin/dominios'
      path: '/dominios'
      fullPath: '/dominios'
      preLoaderRoute: typeof AdminDominiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/diagnostico': {
      id: '/_admin/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof AdminDiagnosticoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/configuracion': {
      id: '/_admin/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cobranza': {
      id: '/_admin/cobranza'
      path: '/cobranza'
      fullPath: '/cobranza'
      preLoaderRoute: typeof AdminCobranzaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bienvenida': {
      id: '/_admin/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof AdminBienvenidaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/backups': {
      id: '/_admin/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/avisos': {
      id: '/_admin/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AdminAvisosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/automatizaciones': {
      id: '/_admin/automatizaciones'
      path: '/automatizaciones'
      fullPath: '/automatizaciones'
      preLoaderRoute: typeof AdminAutomatizacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/auditoria': {
      id: '/_admin/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/arquitectura': {
      id: '/_admin/arquitectura'
      path: '/arquitectura'
      fullPath: '/arquitectura'
      preLoaderRoute: typeof AdminArquitecturaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/servicios/': {
      id: '/_admin/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof AdminServiciosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/clientes/': {
      id: '/_admin/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tareas/$id': {
      id: '/_admin/tareas/$id'
      path: '/$id'
      fullPath: '/tareas/$id'
      preLoaderRoute: typeof AdminTareasIdRouteImport
      parentRoute: typeof AdminTareasRoute
    }
    '/_admin/soporte/$id': {
      id: '/_admin/soporte/$id'
      path: '/$id'
      fullPath: '/soporte/$id'
      preLoaderRoute: typeof AdminSoporteIdRouteImport
      parentRoute: typeof AdminSoporteRoute
    }
    '/_admin/servicios/$id': {
      id: '/_admin/servicios/$id'
      path: '/servicios/$id'
      fullPath: '/servicios/$id'
      preLoaderRoute: typeof AdminServiciosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dominios/$id': {
      id: '/_admin/dominios/$id'
      path: '/$id'
      fullPath: '/dominios/$id'
      preLoaderRoute: typeof AdminDominiosIdRouteImport
      parentRoute: typeof AdminDominiosRoute
    }
    '/_admin/clientes/$id': {
      id: '/_admin/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AdminClientesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminDominiosRouteChildren {
  AdminDominiosIdRoute: typeof AdminDominiosIdRoute
}

const AdminDominiosRouteChildren: AdminDominiosRouteChildren = {
  AdminDominiosIdRoute: AdminDominiosIdRoute,
}

const AdminDominiosRouteWithChildren = AdminDominiosRoute._addFileChildren(
  AdminDominiosRouteChildren,
)

interface AdminSoporteRouteChildren {
  AdminSoporteIdRoute: typeof AdminSoporteIdRoute
}

const AdminSoporteRouteChildren: AdminSoporteRouteChildren = {
  AdminSoporteIdRoute: AdminSoporteIdRoute,
}

const AdminSoporteRouteWithChildren = AdminSoporteRoute._addFileChildren(
  AdminSoporteRouteChildren,
)

interface AdminTareasRouteChildren {
  AdminTareasIdRoute: typeof AdminTareasIdRoute
}

const AdminTareasRouteChildren: AdminTareasRouteChildren = {
  AdminTareasIdRoute: AdminTareasIdRoute,
}

const AdminTareasRouteWithChildren = AdminTareasRoute._addFileChildren(
  AdminTareasRouteChildren,
)

interface AdminRouteChildren {
  AdminArquitecturaRoute: typeof AdminArquitecturaRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminAutomatizacionesRoute: typeof AdminAutomatizacionesRoute
  AdminAvisosRoute: typeof AdminAvisosRoute
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminBienvenidaRoute: typeof AdminBienvenidaRoute
  AdminCobranzaRoute: typeof AdminCobranzaRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminDiagnosticoRoute: typeof AdminDiagnosticoRoute
  AdminDominiosRoute: typeof AdminDominiosRouteWithChildren
  AdminEmailLogsRoute: typeof AdminEmailLogsRoute
  AdminHestiaRoute: typeof AdminHestiaRoute
  AdminNegocioRoute: typeof AdminNegocioRoute
  AdminNotificacionesRoute: typeof AdminNotificacionesRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminOperacionesRoute: typeof AdminOperacionesRoute
  AdminPagosRoute: typeof AdminPagosRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminPlanesRoute: typeof AdminPlanesRoute
  AdminPlantillasRoute: typeof AdminPlantillasRoute
  AdminSoporteRoute: typeof AdminSoporteRouteWithChildren
  AdminTareasRoute: typeof AdminTareasRouteWithChildren
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminWorkflowsRoute: typeof AdminWorkflowsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientesIdRoute: typeof AdminClientesIdRoute
  AdminServiciosIdRoute: typeof AdminServiciosIdRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
  AdminServiciosIndexRoute: typeof AdminServiciosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArquitecturaRoute: AdminArquitecturaRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminAutomatizacionesRoute: AdminAutomatizacionesRoute,
  AdminAvisosRoute: AdminAvisosRoute,
  AdminBackupsRoute: AdminBackupsRoute,
  AdminBienvenidaRoute: AdminBienvenidaRoute,
  AdminCobranzaRoute: AdminCobranzaRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminDiagnosticoRoute: AdminDiagnosticoRoute,
  AdminDominiosRoute: AdminDominiosRouteWithChildren,
  AdminEmailLogsRoute: AdminEmailLogsRoute,
  AdminHestiaRoute: AdminHestiaRoute,
  AdminNegocioRoute: AdminNegocioRoute,
  AdminNotificacionesRoute: AdminNotificacionesRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminOperacionesRoute: AdminOperacionesRoute,
  AdminPagosRoute: AdminPagosRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminPlanesRoute: AdminPlanesRoute,
  AdminPlantillasRoute: AdminPlantillasRoute,
  AdminSoporteRoute: AdminSoporteRouteWithChildren,
  AdminTareasRoute: AdminTareasRouteWithChildren,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminWorkflowsRoute: AdminWorkflowsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientesIdRoute: AdminClientesIdRoute,
  AdminServiciosIdRoute: AdminServiciosIdRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
  AdminServiciosIndexRoute: AdminServiciosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalAvisosRoute: typeof PortalAvisosRoute
  PortalDatosRoute: typeof PortalDatosRoute
  PortalDominiosRoute: typeof PortalDominiosRoute
  PortalPagosRoute: typeof PortalPagosRoute
  PortalTicketsRoute: typeof PortalTicketsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAvisosRoute: PortalAvisosRoute,
  PortalDatosRoute: PortalDatosRoute,
  PortalDominiosRoute: PortalDominiosRoute,
  PortalPagosRoute: PortalPagosRoute,
  PortalTicketsRoute: PortalTicketsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  RecuperarRoute: RecuperarRoute,
  SetupInicialRoute: SetupInicialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
